### ISSUE TITLE
Answer input

### ISSUE THREAD

**Issue by markmos1991** [Jakinlade/Peektionary-Game#8]
**_User Story:_**

As a user, I want to be able to input my answers on the page in response to the image prompt provided in a text format

**_Acceptance Criteria:_**

- There will be an input section on the page where I can type an answer to be checked against the correct answer.
- The answer box should be visible in close proximity to the image.
- The text box should allow me to press enter to submit my answer and tell me if it is correct or incorrect.
- inputted text should be split into words and added to an array, so that each individual word can be checked against a correct answers array.

**Comment by Jakinlade** [comment]
This seems to of broken in current update
